apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-external
  name: events-external
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: events-external
  type: LoadBalancer
status:
  loadBalancer: {}